### ISSUE TITLE
custom folder setup

### ISSUE THREAD

**Issue by npgfg** [bvdputte/kirby-log#8]
Hi,
i am struggling with a custom folder setup following the docs.
My index.php looks like this:

```
include __DIR__ . '/../vendor/autoload.php';

$kirby = new Kirby\Cms\App([
  'roots' => [
    'index'    => __DIR__,
    'base'     => $base = dirname(__DIR__),
    'content'  => $base . '/content',
    'site'     => $base . '/site',
    'storage'  => $storage = $base . '/storage',
    'accounts' => $storage . '/accounts',
    'cache'    => $storage . '/cache',
    'sessions' => $storage . '/sessions',
    'logs'     => $base . '/private/kirbylogs',
  ]
]);

echo $kirby->render();
```

The "/private/kirbylogs" folder exists on the root level with the "content" and "kirby" folder. 
For some reason $site->log still writes to "site/logs/kirbylog.log".
I would expect it to write to "private/kirbylogs/kirbylog.log".

Am i missing something?

Thanks for any help or hints.

**Comment by bvdputte** [comment]
This should not be the case. I've just checked in an existing project of mine, and could not replicate this.

Can you provide more info please?

**Comment by npgfg** [comment]
Sorry for the delay.
It is a DDEV-based local dev environment. 
DDEV config.yaml

```
type: php
docroot: docroot
php_version: "8.2"
webserver_type: apache-fpm
xdebug_enabled: false
additional_hostnames: []
additional_fqdns: []
database:
    type: mariadb
    version: "10.4"
use_dns_when_possible: true
composer_version: "2"
web_environment: []
```

these are all the required packages from the composer.json

```
"require": {
    "getkirby/cms": "^4.7.0",
    "johannschopplich/kirby-headless": "^4.0",
    "vlucas/phpdotenv": "^5.6.1",
    "getkirby/kql": "^2.2",
    "tobimori/kirby-icon-field": "^2.2",
    "johannschopplich/kirby-content-translator": "^2.5.1",
    "relisten/forceutf8": "^1.1",
    "tobimori/kirby-seo": "^1.1.2",
    "deeplcom/deepl-php": "^1.11.1",
    "symfony/http-client": "^7.2.4",
    "nyholm/psr7": "^1.8.2",
    "distantnative/retour-for-kirby": "^5.4.1",
    "bvdputte/kirby-log": "^2.2"
  }
```

not sure what else could be helpful?
